# Generated by Django 4.2.7 on 2023-12-24 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=40)),
                ('number', models.IntegerField(default='')),
                ('year', models.CharField(default='', max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(default='', upload_to='class_htmls')),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('term', models.CharField(blank=True, default='', max_length=60)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='enrolled_students', to='course.student')),
            ],
        ),
    ]
