# Generated by Django 4.2.7 on 2023-12-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
