# Generated by Django 2.2.2 on 2019-07-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='homework',
            field=models.FileField(upload_to='handouts'),
        ),
    ]
