# Generated by Django 2.2.2 on 2019-08-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0010_auto_20190806_0924'),
        ('student_view', '0002_auto_20190730_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Class.Assignment'),
        ),
    ]
