# Generated by Django 2.2.2 on 2019-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class', '0012_remove_course_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_file', models.FileField(upload_to='course_grades')),
                ('course', models.ManyToManyField(to='Class.Course')),
                ('student', models.ManyToManyField(to='Class.Student')),
            ],
        ),
    ]
