# Generated by Django 2.2.2 on 2019-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(default='', max_length=5),
        ),
    ]
