# Generated by Django 4.2.6 on 2023-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_view', '0002_alter_course_class_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Class_File',
            field=models.FileField(default='', upload_to='class_htmls'),
        ),
    ]
