# Generated by Django 2.2.2 on 2019-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_view', '0002_grade_letter_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_file',
        ),
        migrations.AddField(
            model_name='grade',
            name='catagories',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='grade',
            name='points_possible',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='grade',
            name='student_scores',
            field=models.CharField(default='', max_length=200),
        ),
    ]
