# Generated by Django 4.2.6 on 2023-11-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_view', '0003_alter_course_class_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Class_File',
            new_name='source_file',
        ),
    ]
