# Generated by Django 4.2.7 on 2023-12-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_view', '0004_rename_class_file_course_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='instructor',
        ),
        migrations.AddField(
            model_name='assignment',
            name='display_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
