# Generated by Django 2.2.2 on 2019-06-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=40)),
                ('number', models.IntegerField(default='')),
                ('year', models.CharField(default='', max_length=19)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='Class_File',
            field=models.FileField(upload_to='class_htmls'),
        ),
    ]
