# Generated by Django 2.2.2 on 2019-06-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='Class_File',
            field=models.FileField(upload_to='class_htmls'),
        ),
    ]
