# Generated by Django 2.2.2 on 2019-06-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0002_auto_20190624_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
