# Generated by Django 2.2.2 on 2019-07-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0003_auto_20190625_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='Class.Student'),
        ),
    ]
