# Generated by Django 2.2.2 on 2019-07-09 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Class', '0005_auto_20190702_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_students', to='Class.Student'),
        ),
    ]
