# Generated by Django 2.2.2 on 2019-07-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0007_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
