# Generated by Django 2.2.2 on 2019-08-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0010_auto_20190806_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(default='', max_length=5),
        ),
    ]
