# Generated by Django 2.2.2 on 2019-08-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0011_course_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
